---


# tasks file for cleanup
- name: Delete {{ regfiles  }} dir
  file:
    state: absent
    path: "{{ regsfile  }}"

# tasks file for cleanup
- name: Delete {{ destfile  }} dir
  file:
    state: absent
    path: "{{ destfile  }}"
    

- name: Delete {{ regone }} and {{ regtwo }} container
  containers.podman.podman_container:
    name: "{{ item }}"
    state: absent
  loop:
    - "{{ regone }}"
    - "{{ regtwo }}"

- name: Delete the index images
  containers.podman.podman_image:
    name: "{{ item }}"
    state: absent
    force: yes
  loop:
    - "{{ regone }}"
    - "{{ regtwo }}"

- name: Delete container 50051
  shell: sudo podman ps | grep {{ rhindex }}/redhat/redhat-operator-index | sudo podman rm -f $(awk '{print  $1}') 
  become: true
